import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/lib/providers/next-theme-provider";
import { twMerge } from "tailwind-merge";
import { DM_Sans } from "next/font/google";
import db from "../lib/supabase/db";
import AppStateProvider from "../lib/providers/state-provider";
import { SupabaseUserProvider } from "../lib/providers/supabase-user-provider";
import { SocketProvider } from "../lib/providers/socket-provider";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    console.log(db),
    (
      <html lang="en">
        <body className={twMerge("bg-background", inter.className)}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <AppStateProvider>
              <SupabaseUserProvider>
                <SocketProvider>
                {children}
                </SocketProvider>
                </SupabaseUserProvider>
            </AppStateProvider>
          </ThemeProvider>
        </body>
      </html>
    )
  );
}
